#pragma once

#include <stdint.h>

namespace sysycc {

// Enumerates every AST node kind currently modeled by the frontend.
enum class AstKind : uint8_t {
    TranslationUnit,
    BuiltinType,
    NamedType,
    QualifiedType,
    PointerType,
    ArrayType,
    FunctionType,
    StructType,
    UnionType,
    EnumType,
    UnknownType,
    FunctionDecl,
    ParamDecl,
    FieldDecl,
    VarDecl,
    ConstDecl,
    StructDecl,
    UnionDecl,
    EnumeratorDecl,
    EnumDecl,
    TypedefDecl,
    UnknownDecl,
    DeclStmt,
    BlockStmt,
    ExprStmt,
    IfStmt,
    WhileStmt,
    DoWhileStmt,
    ForStmt,
    SwitchStmt,
    CaseStmt,
    DefaultStmt,
    LabelStmt,
    BreakStmt,
    ContinueStmt,
    GotoStmt,
    ReturnStmt,
    UnknownStmt,
    IntegerLiteralExpr,
    FloatLiteralExpr,
    CharLiteralExpr,
    StringLiteralExpr,
    IdentifierExpr,
    SizeofTypeExpr,
    UnaryExpr,
    PrefixExpr,
    PostfixExpr,
    BinaryExpr,
    CastExpr,
    ConditionalExpr,
    AssignExpr,
    CallExpr,
    IndexExpr,
    MemberExpr,
    InitListExpr,
    UnknownExpr,
};

} // namespace sysycc
