#pragma once

namespace sysycc {

// Enumerates every AST node kind currently modeled by the frontend.
enum class AstKind {
    TranslationUnit,
    BuiltinType,
    PointerType,
    StructType,
    EnumType,
    UnknownType,
    FunctionDecl,
    ParamDecl,
    FieldDecl,
    VarDecl,
    ConstDecl,
    StructDecl,
    EnumeratorDecl,
    EnumDecl,
    TypedefDecl,
    UnknownDecl,
    DeclStmt,
    BlockStmt,
    ExprStmt,
    IfStmt,
    WhileStmt,
    DoWhileStmt,
    ForStmt,
    SwitchStmt,
    CaseStmt,
    DefaultStmt,
    BreakStmt,
    ContinueStmt,
    ReturnStmt,
    UnknownStmt,
    IntegerLiteralExpr,
    FloatLiteralExpr,
    CharLiteralExpr,
    StringLiteralExpr,
    IdentifierExpr,
    UnaryExpr,
    PrefixExpr,
    PostfixExpr,
    BinaryExpr,
    AssignExpr,
    CallExpr,
    IndexExpr,
    MemberExpr,
    InitListExpr,
    UnknownExpr,
};

} // namespace sysycc
